# Generated by Django 5.1.3 on 2026-08-30 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INITIAL_BALANCE', 'Начальный остаток'), ('RECEIPT', 'Приход'), ('SALE', 'Продажа'), ('SALE_RETURN', 'Возврат покупателя'), ('SUPPLIER_RETURN', 'Возврат поставщику'), ('WRITE_OFF', 'Списание'), ('ADJUSTMENT_IN', 'Корректировка плюс'), ('ADJUSTMENT_OUT', 'Корректировка минус'), ('SALE_CANCEL', 'Отмена продажи'), ('RECEIPT_CANCEL', 'Отмена прихода')], db_index=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorymovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
            ],
            options={
                'verbose_name': 'Корректировка склада',
                'verbose_name_plural': 'Корректировки склада',
                'permissions': [('adjust_stock', 'Can adjust stock')],
            },
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_i_product_c37810_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_0d8590_idx'),
        ),
    ]
