# Generated by Django 5.1.15 on 2026-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at'], 'verbose_name': '库存流水 / Движение склада', 'verbose_name_plural': '库存流水 / Движения склада'},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'permissions': [('adjust_stock', 'Can adjust stock')], 'verbose_name': '库存调整 / Корректировка склада', 'verbose_name_plural': '库存调整 / Корректировки склада'},
        ),
    ]
