# Generated by Django 5.1.3 on 2026-08-30 17:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('POSTED', 'Проведен'), ('CANCELLED', 'Отменен')], db_index=True, default='DRAFT', max_length=20)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='products.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.stockreceipt')),
            ],
            options={
                'verbose_name': 'Строка прихода',
                'verbose_name_plural': 'Строки прихода',
            },
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['status', 'date'], name='purchases_s_status_b43c65_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['created_at'], name='purchases_s_created_c39428_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreceiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='receipt_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='stockreceiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='receipt_item_cost_price_gte_0'),
        ),
    ]
