# Generated by Django 5.1.15 on 2026-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreceipt',
            options={'verbose_name': '入库单 / Приход', 'verbose_name_plural': '入库单 / Приходы'},
        ),
        migrations.AlterModelOptions(
            name='stockreceiptitem',
            options={'verbose_name': '入库明细 / Строка прихода', 'verbose_name_plural': '入库明细 / Строки прихода'},
        ),
    ]
