# Generated by Django 5.1.15 on 2026-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户 / Клиент', 'verbose_name_plural': '客户 / Клиенты'},
        ),
    ]
