# Generated by Django 5.1.15 on 2026-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类 / Категория', 'verbose_name_plural': '分类 / Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_cost_price', 'Can view cost price'), ('view_profit', 'Can view gross profit')], 'verbose_name': '商品 / Товар', 'verbose_name_plural': '商品 / Товары'},
        ),
    ]
