# Generated by Django 5.1.15 on 2026-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idempotencykey',
            options={'verbose_name': '防重复请求 / Idempotency Key', 'verbose_name_plural': '防重复请求 / Idempotency Keys'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('cancel_sale', 'Can cancel sale'), ('correct_sale', 'Can correct historical sale'), ('view_profit', 'Can view sale gross profit'), ('view_cost_price', 'Can view sale cost price')], 'verbose_name': '销售单 / Продажа', 'verbose_name_plural': '销售单 / Продажи'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': '销售明细 / Строка продажи', 'verbose_name_plural': '销售明细 / Строки продажи'},
        ),
        migrations.AlterModelOptions(
            name='salereturn',
            options={'verbose_name': '退货单 / Возврат', 'verbose_name_plural': '退货单 / Возвраты'},
        ),
    ]
